# Called from tasks/voms-accounts.yml
# Iterates over a VO to create pool accounts
- name: Create pool accounts
  user:
    name: '{{ _vodata.account_prefix }}{{ "%03d" | format(ansible_loop.index) }}'
    uid: '{{ _vodata.base_uid + 1 * ansible_loop.index }}'
    group: '{{ _vodata.name }}'
    comment: '{{ _vodata.name }} pool account user'
    home: '/home/{{ name }}'
    shell: '/bin/bash'
    create_home: '{{ voms_create_user_dir }}'
  loop: "{{ range(1 , vo_pool_accounts_count)  | list }}"
  loop_control:
    extended: true

