---
# FIXME: the UID/GIDs threshold is quite arbitrary

# Select VOMS groups 
- name: Get group information
  ansible.builtin.getent:
    database: group

- name: Define query to filter gid > 9000 and exclude 'nobody'
  set_fact:
    gquery: "[?to_number(value[1]) > `9000` && key != 'nobody'].key"

- name: Create list of groups with gid > 9000 excluding 'nobody'
  set_fact:
    tbd_voms_groups: "{{ getent_group | dict2items | json_query(gquery) }}"

# Select VOMS users
- name: Get user information
  ansible.builtin.getent:
    database: passwd

- name: Define query to filter uid > 9000 and exclude 'nobody'
  set_fact:
    uquery: "[?to_number(value[1]) > `9000` && key != 'nobody'].key"

- name: Create list of users with uid > 9000 excluding 'nobody'
  set_fact:
    tbd_voms_users: "{{ getent_passwd | dict2items | json_query(uquery) }}"

# Delete VOMS users
- name: Delete VOMS users
  user:
    name: '{{ item }}'
    state: absent
  loop: "{{ tbd_voms_users }}"

# Delete local users
- name: Delete local users
  user:
    name: '{{ item.account }}'
    state: absent
  loop: "{{ gridsite_local_users }}"

# Delete VOMS groups
- name: Delete VOMS groups
  group:
    name: '{{ item }}'
    state: absent
  loop: "{{ tbd_voms_groups }}"
