---
# Common variables
- name: Get supported VOs info
  include_vars:
    file: 'vars/supported_vos.yaml'

# Dynamic generation of VO data from EGI API
- name: Generate VO data
  local_action: command {{ role_path }}/scripts/generates_yaml_vo_data.sh
  #./scripts/generates_yaml_vo_data.sh


# VO data reading, a bit complex with three operations
# Can likely be simplified.
- name: Read vo data files in vars
  include_vars:
    file: 'generated_vars/vo/params/{{ item }}.yml'
  loop: "{{ supported_vos }}"
  register: supported_vos_data

- name: Combine configs into one dict
  set_fact:
    supported_vos_data_dict: "{{ dict(supported_vos_data.results | json_query('[].[item, ansible_facts]')) }}"

- name: Combine configs into one list
  set_fact:
    supported_vos_data_list: "{{ supported_vos_data_dict | dict2items | map(attribute='value') }}"

# Client configuration
- name: Configure voms client
  include_tasks: 'voms-client.yml'
  tags:
    - all

# Gridmap configuration
#- name: Configure voms gridmap
#  include_tasks: 'voms-gridmap.yml'
#  tags:
#    - ce_arc

# Account configuration
- name: Configure voms accounts
  include_tasks: 'voms-accounts.yml'
  tags:
    - ce_arc
    - grid_wn
