---
# Client configuration
- name: Configure voms client
  include_tasks: 'voms-client.yml'

# Account configuration
- name: Configure voms accounts
  include_tasks: 'voms-accounts.yml'
  when:
    - "voms_create_accounts is defined and ('ce_arc' in group_names or 'grid_wn' in group_names)"

# Slurm configuration
- name: Configure slurm
  include_tasks: 'voms-slurm.yml'
  when:
    - "'ce_arc' in group_names"

