---
# Common variables
- name: Get supported VOs info
  include_vars:
    file: vars/supported_vos.yaml
 
 - name: Get all the VOMS info
  include_vars:
    file: "files/data.yml"
    name: vo_voms

# Restricts request to supported VO if defined
- name: Set VOMS data query
  set_fact:
    voms_data_query: "data[?{{ [\"name == '\"] | product(supported_vos) | map(\"join\") | product([\"'\"]) | map(\"join\") | join(\"||\") }}]"
  when: supported_vos is defined

# Client configuration
- name: Configure voms client
  include_tasks: voms-client.yml
  tags:
    - all

# Account configuration
- name: Configure voms accounts
  include_tasks: voms-accounts.yml
  tags:
    - all # FIXME
