---
# Client configuration
- name: Configure voms client
  include_tasks: 'voms-client.yml'

# Account configuration
- name: Configure voms accounts
  include_tasks: 'voms-accounts.yml'
  when:
    - "'ce_arc' in group_names or 'grid_wn' in group_names"

# Slurm configuration
- name: Configure slurm accounts
  include_tasks: 'voms-slurm-sacctmgr.yml'
  when:
    - "'ce_arc' in group_names"

