---
# Set UID_MAX
- name: Set UID_MAX in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UID_MAX'
    line: 'UID_MAX                 200000'
    state: present
    backup: yes

# Set GID_MAX
- name: Set GID_MAX in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^GID_MAX'
    line: 'GID_MAX                 200000'
    state: present
    backup: yes

# Create VO main groups
- name: Create vo groups
  group:
    name: '{{ item.group }}'
    gid: '{{ item.gid }}'
    state: present
  loop: '{{ gridsite_supported_vos_data_list }}'

# Debug print gridsite_supported_vos_data_list
#- name: Debug print gridsite_supported_vos_data_list
#  debug:
#    msg: "{{ gridsite_supported_vos_data_list }}"

# Debug print VO subgroups
#- name: Debug print _role_pool_accounts
#  debug:
#    msg: "{{ item.1.group }}"
#    msg: "{{ item.1.gid }}"
#  loop: '{{ gridsite_supported_vos_data_list | subelements("roles", "skip_missing=True") }}'

# Create VO subgroups
- name: Create VO subgroups
  group:
    name: '{{ item.1.group }}'
    gid: '{{ item.1.gid }}'
    state: present
  loop: '{{ gridsite_supported_vos_data_list | subelements("roles", "skip_missing=True") }}'
  when: item.1.gid is defined

# Create VO pool accounts
- name: Create VO main pool accounts
  user:
    name: '{{ item.1.account }}'
    uid: '{{ item.1.uid }}'
    group: '{{ item.0.group }}'
    state: present
    comment: 'VO {{ item.0.name }} pool account'
    shell: /bin/bash
    home: '/home/{{ item.1.account }}'
    create_home: '{{ voms_create_user_dir }}'
  loop: '{{ gridsite_supported_vos_data_list | subelements("pool_accounts", "skip_missing=True") }}'

# Create VO roles pool accounts
# As subelement of subelement can't work, use task. 
- name: Create VO roles pool accounts
  include_tasks: 'tasks/voms-role-accounts.yml'
  loop: '{{ gridsite_supported_vos_data_list | subelements("roles", "skip_missing=True") }}'
  loop_control:
    loop_var: '_roles_data'
