---

- name: Ensure Required VOMS directories
  file:
    path: "{{ item }}"
    state: "directory"
    mode: 0755
    owner: "root"
    group: "root"
  loop:
    - "{{ vomsdir_dir }}"
    - "{{ vomses_dir }}"

- name: Create LSC directories
  file:
    path: "{{ vomsdir_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"
  loop: "{{ supported_vos }}"

# LSC files should have the format:
# certificate DN
# CA signing authority
# Path is /etc/vomsdir/vo-name/voms-host.lsc

- name: Print variables
  debug:
    msg: "Supported VOs : {{ supported_vos }}"
  when: supported_vos is defined
- name: Ensure LSC files present
  copy:
    dest: "{{ vomsdir_dir }}/{{ item.name }}/{{ item.hostname }}.lsc"
    content: |
      {{ item.DN }}
      {{ item.CA_DN }}
    mode: 0644
    owner: "root"
    group: "root"
  loop:
    "{{ supported_vos_data_dict | subelements('voms_servers') | to_json |}}"

- name: Ensure vomses files present
  copy:
    dest: "{{ vomses_dir }}/{{ item.name }}-{{ item.hostname }}"
    content: >
      "{{ item.name }}" "{{ item.hostname }}" "{{ item.port }}" "{{ item.DN }}"
      "{{ item.name }}"
    mode: 0644
    owner: "root"
    group: "root"
  loop:
    "{{ vo_voms | json_query(voms_data_query) | subelements('voms') | to_json |
    from_json | json_query('[*].{name: [0].name, hostname: [1].hostname, DN:
    [1].DN, port: [1].port}') }}"
