---
- name: Create gridmapdir directory
  file:
    path: '{{ gridmapdir_dir }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0770

# Create gridmapdir accounts
- name: Create gridmapdir accounts
  file:
    path: '{{ gridmapdir_dir }}/{{ item.name }}'
    state: touch
    owner: root
    group: root
    mode: 0644
  loop: '{{ grid_users }}'

# Install nordugridmap
- name: Install nordugridmap
  yum:
    name: 'nordugrid-arc6-nordugridmap'
    state: latest

# edg-mkgridmap configuration file
# FIXME: should be in templates
#- name: Create edg-mkgridmap configuration file
#  template:
#    src: 'files/edg-mkgridmap.conf.j2'
#    dest: '/etc/edg-mkgridmap.conf'
#    owner: root
#    group: root
#    mode: 0644


# For now, if nothing else works, at least this will
- name: Static grid-mapfile
  template:
    src: 'templates/grid-mapfile.j2'
    dest: '/etc/grid-security/grid-mapfile'
    owner: root
    group: root
    mode: 0644
