---
- name: Create gridmapdir directory
  file:
    path: '{{ gridmapdir_dir }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0770

# Restricts request to supported VO if defined
- name: Set VOMS data query
  set_fact:
    voms_data_query: "data[?{{ [\"name == '\"] | product(supported_vos) | map(\"join\") | product([\"'\"]) | map(\"join\") | join(\"||\") }}]"
  when: supported_vos is defined  

# User list
- name: Get user list
  include_vars:
    file: 'vars/user_list.yaml'

# Create gridmapdir accounts
#- name: Create gridmapdir accounts
#  file:
#    path: '{{ gridmapdir_dir }}/{{ item.name }}'
#    state: touch
#    owner: root
#    group: root
#    mode: 0644
#  loop: '{{ grid_users }}'


# Dict of supported VOs
- name: Get supported VOs
  set_fact:
    supported_vos_dict: "{{ vo_voms | json_query(voms_data_query) }}"


# edg-mkgridmap configuration file
- name: Create edg-mkgridmap configuration file
  template:
    src: 'files/edg-mkgridmap.conf.j2'
    dest: '/etc/edg-mkgridmap.conf'
    owner: root
    group: root
    mode: 0644

