---
# FIXME: in /etc/login.defs UID_MAX and GID_MAX where manually set
# as the default is only 60000.

# Create groups
- name: Create groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  loop: '{{ grid_groups }}'

# Create accounts
- name: Create accounts
  user:
    name: '{{ item.name }}'
    password: '**NP**'
    uid: '{{ item.uid }}'
    group: '{{ item.group }}'
    groups: '{{ item.groups }}'
    home: '/home/{{ item.name }}'
    shell: '/bin/bash'
    create_home: '{{ voms_create_user_dir }}'
  loop: '{{ grid_users }}'
