---
# FIXME: that's slurm configuration, why here?
# (because it's where we deal with aaccounts)

# Configure slurm sacctmgr with relevant users and groups

- name: Create config file
  template:
    src: sacctmgr.cfg.j2
    dest: /tmp/sacctmgr.cfg

# Load configuration  in sacctmgr
- name: Load configuration in sacctmgr
  shell: sacctmgr -i load /tmp/sacctmgr.cfg

