---
- name: Create gridmapdir directory
  file:
    path: '{{ gridmapdir_dir }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0770

# Restricts request to supported VO if defined
- name: Set VOMS data query
  set_fact:
    voms_data_query: "data[?{{ [\"name == '\"] | product(supported_vos) | map(\"join\") | product([\"'\"]) | map(\"join\") | join(\"||\") }}]"
  when: supported_vos is defined  

# User list
- name: Get user list
  include_vars:
    file: 'vars/user_list.yaml'

# Group list
- name: Get group list
  include_vars:
    file: 'vars/group_list.yaml'

# Create gridmapdir accounts
- name: Create gridmapdir accounts
  file:
    path: '{{ gridmapdir_dir }}/{{ item.name }}'
    state: touch
    owner: root
    group: root
    mode: 0644
  loop: '{{ grid_users }}'


# Dict of supported VOs
- name: Get supported VOs
  set_fact:
    supported_vos_dict: '{{ vo_voms | json_query(voms_data_query) }}'

# Install edg-mkgridmap
- name: Install edg-mkgridmap
  yum:
    name: 'edg-mkgridmap'
    state: latest

# edg-mkgridmap configuration file
- name: Create edg-mkgridmap configuration file
  template:
    src: 'files/edg-mkgridmap.conf.j2'
    dest: '/etc/edg-mkgridmap.conf'
    owner: root
    group: root
    mode: 0644

# Generate grid-mapfile from a cron job runnnig every 3 hours
- name: Generate grid-mapfile
  cron:
    name: 'edg-mkgridmap cron job'
    minute: '46'
    hour: '0-23/3'
    job: 'edg-mkgridmap -c /etc/edg-mkgridmap.conf'
    cron_file: '/etc/cron.d/edg-mkgridmap.cron'
    user: root

# FIXME: in /etc/login.defs UID_MAX and GID_MAX where manually set
# as the default is only 60000.

# Create groups
- name: Create groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  loop: '{{ grid_groups }}'

# Create accounts
- name: Create accounts
  user:
    name: '{{ item.name }}'
    password: '**NP**'
    uid: '{{ item.uid }}'
    group: '{{ item.group }}'
    groups: '{{ item.groups }}'
    home: '/home/{{ item.name }}'
    shell: '/bin/bash'
  loop: '{{ grid_users }}'