---
# FIXME: in /etc/login.defs UID_MAX and GID_MAX where manually set
# as the default is only 60000.

# Create VO main groups
- name: Create vo groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.base_uid }}'
    state: present
  loop: '{{ supported_vos_data_list }}'
  tags:
    - toto

# Create VO subgroups
- name: Create VO subgroups
  group:
    name: '{{ item.0.account_prefix}}{{ item.1.suffix }}'
    gid: '{{ item.0.base_uid +  1 * ( item.0.voms_mappings.index(item.1) + 1 ) }}'
    state: present
  loop: '{{ supported_vos_data_list | subelements("voms_mappings", "skip_missing=True") }}'
  loop_control:
    extended: true
  tags:
    - toto

# Create VO pool accounts
- name: Create VO main pool accounts
  include_tasks: 'tasks/create_pool_accounts.yml' 
  loop: '{{ supported_vos_data_list }}'
  loop_control:
    loop_var: '_vodata'

# Create VO subgroups pools
- name: Create VO subgroups pools
  include_tasks: 'tasks/create_vo_grp_pool_accounts.yml'
  loop: '{{ supported_vos_data_list | subelements("voms_mappings", "skip_missing=True") }}'
  loop_control:
    loop_var: '_vodata'

