---
- name: Ensure Required VOMS directories
  file:
    path: "{{ item }}"
    state: "directory"
    mode: 0755
    owner: "root"
    group: "root"
  loop:
    - "{{ voms_vomsdir_dir }}"
    - "{{ voms_vomses_dir }}"

- name: Create LSC directories
  file:
    path: "{{ voms_vomsdir_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"
  loop: "{{ gridsite_supported_vos }}"

- name: Ensure LSC files present
  copy:
    dest: "{{ voms_vomsdir_dir }}/{{ item.0.name }}/{{ item.1.name }}.lsc"
    content: |
      {{ item.1.DN  }}
      {{ item.1.CA_DN }}
    mode: 0644
    owner: "root"
    group: "root"
  loop:
    "{{ gridsite_supported_vos_data_list | subelements('voms_servers', 'skip_missing=True')  }}"
  when: 
    item.1.DN is defined

# LSC files should have the format:
# certificate DN
# CA signing authority
# Path is /etc/vomsdir/vo-name/voms-host.lsc
- name: Ensure vomses files present
  copy:
    dest: "{{ voms_vomses_dir }}/{{ item.0.name }}-{{ item.1.name }}"
    content: >
      "{{ item.0.name }}" "{{ item.1.host }}" "{{ item.1.port }}" "{{ item.1..DN }}"
      "{{ item.0.name }}"
    mode: 0644
    owner: "root"
    group: "root"
  loop:
    "{{ gridsite_supported_vos_data_list | subelements('voms_servers', 'skip_missing=True')  }}"
  when: 
    item.voms_servers.DN is defined